name: Build and deploy

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U $POSTGRES_USER"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Instalar python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: |
          python -m venv BACKEND/.venv
          source BACKEND/.venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r BACKEND/requirements.txt

      - name: Criar arquivo .env
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> BACKEND/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> BACKEND/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> BACKEND/.env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> BACKEND/.env

      - name: Run Backend Test
        run: |
          source BACKEND/.venv/bin/activate
          python -m pytest BACKEND/case_tests.py
